### ISSUE TITLE
Make Azure Storage account optional when using MSSQL custom backend

### ISSUE THREAD

**Issue by cgillum** [scale-tone/DurableFunctionsMonitor#115]
### Scenario
Durable Functions allows you to deploy apps in Kubernetes with an MSSQL backend and zero internet connectivity. This means it works without any Azure Storage connection string configuration. I wanted to deploy DFM as a container alongside a Durable apps with a SQL backend and no external service dependencies.

### Issue
If I don't specify an Azure Storage connection string when running DFM (meaning, no value for `AzureWebJobsStorage`), the main HTTP trigger entry point fails with an ArgumentNullException.

```
Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: DfmServeStaticsFunction
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'connectionString')
   at Microsoft.WindowsAzure.Storage.CloudStorageAccount.Parse(String connectionString)
   at DurableFunctionsMonitor.DotNetBackend.CustomTemplates.GetCustomMetaTagCodeFromStorageAsync()
   at DurableFunctionsMonitor.DotNetBackend.ServeStatics.DfmServeStaticsFunction(HttpRequest req, String p1, ExecutionContext context, ILogger log)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeWithTimeoutAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 555
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 503
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 281
```

Looking at the code, it seems this is required when looking up some optional metadata in Azure Storage. Since this metadata is optional anyways, maybe we can gracefully skip metadata loading if there is no Azure Storage connection string configured (though I'm not sure if there might be any other dependencies).

**Comment by scale-tone** [comment]
That makes perfect sense, @cgillum , and a tiny fix is out there already. 
Didn't know Functions can work even without any Storage provided, but turns out they can (with `AzureWebJobsSecretStorageType` set to `files`), that's great news!

**Comment by MaximRouiller** [comment]
We may at some point want to check for Netherite support as well. Have we tried Netherite? Does DFM have any hard dependencies besides the Functions HTTP API?

https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-storage-providers

**Comment by scale-tone** [comment]
@MaximRouiller , DfMon should work with Netherite in 'injected' mode (added as NuGet package into the Functions project itself). Supporting it in other modes (standalone, VsCode ext) is not yet possible, because Netherite provider cannot work in readonly mode. https://github.com/microsoft/durabletask-netherite/issues/38
